game_root: "/path/to/CK3/game"
mod_root: "/path/to/your/mod"
custom_comment_prefix: "# YOUR_CUSTOM_PREFIX:"
files:
  # Relative paths apply to both game_root and mod_root as files should mirror each other
  - relative_path: path/to/your/file.txt
    # List of entity keys that have been modified in the mod version of the file
    modified_entity_keys:
      - event_name.0001
      - event_name.0002
  # ...etc
  # Real Example::
  - relative_path: events/interaction_events/character_interaction_events.txt
    modified_entity_keys:
      - char_interaction.0160
      - char_interaction.0231
