game_root: /mnt/c/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game
files:
  - relative_path: events/councillor_task_events/spymaster_task_events.txt
    modified_entity_keys:
      - spymaster_task.0347
  - relative_path: events/interaction_events/character_interaction_events.txt
    modified_entity_keys:
      - char_interaction.0160
      - char_interaction.0231
  - relative_path: events/interaction_events/marriage_interaction_events.txt
    modified_entity_keys:
      - marriage_interaction.0010
  - relative_path: events/scheme_events/seduce_scheme/seduce_scheme_outcome_events.txt
    modified_entity_keys:
      - seduce_outcome.3901
  - relative_path: events/scheme_events/hostile_scheme_discovery_events.txt
    modified_entity_keys:
      - hostile_scheme_discovery.1002
      - hostile_scheme_discovery.2001
  - relative_path: events/birth_events.txt
    modified_entity_keys:
      - birth.1010
